/*
 * Kubeflow Auth
 *
 * Access Management API.
 *
 * API version: 1.0.0
 * Contact: kubeflow-engineering@google.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"k8s.io/client-go/kubernetes/scheme"
	log "github.com/sirupsen/logrus"
	"net/http"

	"github.com/kubeflow/kubeflow/components/access-management/kfam"
	profile "github.com/kubeflow/kubeflow/components/access-management/pkg/apis/kubeflow/v1alpha1"
)

func main() {
	log.Printf("Server started")

	profile.AddToScheme(scheme.Scheme)

	profileClient, err := kfam.NewProfileConfig()
	if err != nil {
		log.Print(err)
		panic(err)
	}

	router := kfam.NewRouter(profileClient)

	log.Fatal(http.ListenAndServe(":8081", router))
}
