# Generated by Django 4.0.1 on 2022-01-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
