# Generated by Django 4.0.1 on 2022-01-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provision_response', models.CharField(max_length=255)),
            ],
        ),
    ]
