FROM davidspek/kubeflow-ubuntu-jupyter-base:0.5

COPY requirements-cpu.txt .
RUN python3 -m pip install -r \
    requirements-cpu.txt --quiet --no-cache-dir \
    -f https://download.pytorch.org/whl/torch_stable.html \
    && rm -f requirements.txt
