apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: tensorboards-web-app
        image: ghcr.io/kubeflow/kubeflow/tensorboards-web-app
        ports:
        - containerPort: 5000
        env:
        - name: APP_PREFIX
          value: placeholder
        - name: USERID_HEADER
          value: placeholder
        - name: USERID_PREFIX
          value: placeholder
        - name: APP_SECURE_COOKIES
          value: placeholder
        - name: METRICS
          value: placeholder
      serviceAccountName: service-account
