# Load the shared modules dir to PYTHONPATH
all: run-default

run-default:
	cd default && PYTHONPATH=${PYTHONPATH}:${CURDIR} python run.py

run-rok:
	cd rok && PYTHONPATH=${PYTHONPATH}:${CURDIR} python run.py