# Generated by Django 4.0 on 2022-01-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EphemeralCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=20, unique=True)),
                ('version', models.CharField(default='3.0.0', max_length=7)),
                ('number_of_replicas', models.IntegerField(default=3)),
                ('offset_topic_replication_factor', models.IntegerField(default=3)),
                ('transaction_state_log_replication_factor', models.IntegerField(default=3)),
                ('transaction_state_log_min', models.IntegerField(default=3)),
                ('default_replication_factor', models.IntegerField(default=3)),
                ('min_insync_replicas', models.IntegerField(default=2)),
                ('inter_broker_protocol_version', models.CharField(default='3.0', max_length=7)),
                ('storage_type', models.CharField(default='ephemeral', max_length=15)),
                ('zookeeper_replicas', models.IntegerField(default=3)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
