# Generated by Django 4.0.1 on 2022-01-16 06:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('broker_type', models.CharField(max_length=255)),
                ('zookeeper_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KafkaBridge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kafka.kafkacluster')),
            ],
        ),
        migrations.CreateModel(
            name='KafkaTopic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kafka.kafkacluster')),
                ('partitions', models.IntegerField(default=1)),
                ('replicas', models.IntegerField(default=1)),
                ('retention', models.CharField(default='7200000', max_length=255)),
                ('segment', models.CharField(default='1073741824', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KafkaUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kafka.kafkacluster')),
            ],
        ),
        migrations.CreateModel(
            name='KafkaVirtualService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kafka.kafkacluster')),
            ],
        ),
    ]
