# Generated by Django 4.0 on 2022-01-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('namespace', models.CharField(max_length=50)),
                ('gateway', models.CharField(default='kubeflow/kubeflow-gateway', max_length=255)),
                ('hosts', models.CharField(default="'*'", max_length=255)),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('destination', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
