# Generated by Django 4.0.1 on 2022-01-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafkatopic',
            name='cluster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kafka.kafkacluster'),
        ),
        migrations.AlterField(
            model_name='kafkauser',
            name='cluster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kafka.kafkacluster'),
        ),
    ]
