# Generated by Django 4.0.1 on 2022-01-16 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kafka', '0002_alter_kafkatopic_cluster_alter_kafkauser_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafkacluster',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
