# Generated by Django 4.0.1 on 2022-01-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0003_kafkacluster_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafkacluster',
            name='initial_service_account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kafkacluster',
            name='initial_service_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kafkacluster',
            name='initial_topic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
