# Generated by Django 4.0.1 on 2022-01-17 01:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0004_kafkacluster_initial_service_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaBroker',
            fields=[
                ('version', models.CharField(default='3.0.0', max_length=255)),
                ('replicas', models.PositiveSmallIntegerField(default=3)),
                ('broker_type', models.CharField(choices=[('J', 'jbod'), ('E', 'ephemeral')], default='E', max_length=255)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='broker', serialize=False, to='kafka.kafkacluster')),
            ],
        ),
        migrations.CreateModel(
            name='KafkaBrokerVolume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(default='persistent-claim', max_length=255)),
                ('size', models.IntegerField()),
                ('delete_claim', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KafkaZookeeper',
            fields=[
                ('replicas', models.PositiveSmallIntegerField(default=3)),
                ('zookeeper_type', models.CharField(choices=[('J', 'jbod'), ('E', 'ephemeral')], default='E', max_length=255)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='zookeeper', serialize=False, to='kafka.kafkacluster')),
            ],
        ),
        migrations.CreateModel(
            name='KafkaZookeeperVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='persistent-claim', max_length=255)),
                ('size', models.IntegerField()),
                ('delete_claim', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='kafkacluster',
            name='broker_type',
        ),
        migrations.RemoveField(
            model_name='kafkacluster',
            name='zookeeper_type',
        ),
        migrations.AlterField(
            model_name='kafkabridge',
            name='cluster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cluster_bridge', serialize=False, to='kafka.kafkacluster'),
        ),
        migrations.AlterField(
            model_name='kafkatopic',
            name='cluster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='topics', serialize=False, to='kafka.kafkacluster'),
        ),
        migrations.AlterField(
            model_name='kafkauser',
            name='cluster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cluster_users', serialize=False, to='kafka.kafkacluster'),
        ),
        migrations.AlterField(
            model_name='kafkavirtualservice',
            name='cluster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cluster_virtual_service', serialize=False, to='kafka.kafkacluster'),
        ),
        migrations.CreateModel(
            name='KafkaBrokerListeners',
            fields=[
                ('plain_name', models.CharField(choices=[('P', 'plain'), ('T', 'tls')], default='P', max_length=255)),
                ('plain_port', models.IntegerField(default=9092)),
                ('plain_type', models.CharField(choices=[('I', 'internal')], default='I', max_length=255)),
                ('tls_type', models.BooleanField(default=False)),
                ('tls_name', models.CharField(choices=[('P', 'plain'), ('T', 'tls')], default='T', max_length=255)),
                ('tls_port', models.IntegerField(default=9093)),
                ('tls_tls_type', models.BooleanField(default=True)),
                ('broker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='listeners', serialize=False, to='kafka.kafkabroker')),
            ],
        ),
        migrations.CreateModel(
            name='KafkaConfig',
            fields=[
                ('offsets_topic_replication_factor', models.PositiveSmallIntegerField(default=3)),
                ('transaction_state_log_replication_factor', models.PositiveSmallIntegerField(default=3)),
                ('transaction_state_log_min_isr', models.PositiveSmallIntegerField(default=2)),
                ('default_replication_factor', models.PositiveSmallIntegerField(default=3)),
                ('min_insync_replicas', models.PositiveSmallIntegerField(default=2)),
                ('inter_broker_protocol_version', models.CharField(default='3.0', max_length=20)),
                ('broker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='configurations', serialize=False, to='kafka.kafkabroker')),
            ],
        ),
    ]
