# Generated by Django 4.0.1 on 2022-01-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0005_kafkabroker_kafkabrokervolume_kafkazookeeper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafkatopic',
            name='retention',
            field=models.BigIntegerField(default=7200000),
        ),
        migrations.AlterField(
            model_name='kafkatopic',
            name='segment',
            field=models.BigIntegerField(default=1073741824),
        ),
    ]
