FROM public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter:master-b3fe73b2

COPY --chown=jovyan:users requirements-cpu.txt .
RUN python3 -m pip install -r \
    requirements-cpu.txt --quiet --no-cache-dir \
    -f https://download.pytorch.org/whl/torch_stable.html \
    && rm -f requirements-cpu.txt
