apiVersion: kubeflow.org/v1beta1
kind: Notebook
metadata:
  name: {name}
  namespace: "{namespace}"
  labels:
    app: {name}
  annotations:
    notebooks.kubeflow.org/server-type: ""
spec:
  template:
    spec:
      serviceAccountName: {serviceAccount}
      containers:
        - name: {name}
          image: ""
          volumeMounts: []
          env: []
          resources:
            requests:
              cpu: "0.1"
              memory: "0.1Gi"
      volumes: []
      tolerations: []
