apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {name}
spec:
  kafka:
    version: 3.0.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {kafkastoragesize1}
        deleteClaim: false
      - id: 1
        type: persistent-claim
        size: {kafkastoragesize2}
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: {zookeeperstoragesize}
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
