FROM davidspek/kubeflow-buster-base:0.14-pip

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

COPY requirements-gpu.txt .
RUN python3 -m pip install -r \
    requirements-gpu.txt --quiet --no-cache-dir \
    -f https://download.pytorch.org/whl/torch_stable.html

COPY requirements.txt .
RUN python3 -m pip install -r \
    requirements.txt --quiet --no-cache-dir
