{
  global: {
    // User-defined global parameters; accessible to all component and environments, Ex:
    // replicas: 4,
  },
  components: {
    // Component-level parameters, defined initially from 'ks prototype use ...'
    // Each object below should correspond to a component in the components/ directory    
    "kubeflow-core": {
      cloud: "null",
      disks: "null",
      name: "kubeflow-core",
      namespace: "cnn-test1",
      tfJobImage: "gcr.io/tf-on-k8s-dogfood/tf_operator:v20171214-0bd02ac",
    },
    "tf-job": {
      batch_size: 32,
      image: "gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3",
      image_gpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      model: "resnet50",
      name: "tf-job",
      namespace: "cnn-test1",
      numGpus: 0,
      numMasters: 1,
      numPs: 0,
      numWorkers: 0,
      num_gpus: 1,
    },
    "tf-cnn1": {
      batch_size: 32,
      image: "gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3",
      imageGpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      image_gpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      model: "resnet50",
      name: "tf-cnn1",
      namespace: "cnn-test1",
      numGpus: 0,
      numMasters: 1,
      numPs: 0,
      numWorkers: 0,
      num_gpus: 0,
    },
    "cnn-test2": {
      batch_size: 32,
      image: "gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3",
      image_gpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      model: "resnet50",
      name: "cnn-test2",
      namespace: "cnn-test",
      numGpus: 0,
      numPs: 0,
      numWorkers: 1,
      num_gpus: 0,
    },
    "cnn-test3": {
      batch_size: 32,
      image: "gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3",
      image_gpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      model: "resnet50",
      name: "cnn-test3",
      namespace: "cnn-test",
      numGpus: 0,
      numPs: 1,
      numWorkers: 1,
      num_gpus: 0,
    },
    "cnn-test4": {
      batch_size: 32,
      image: "gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3",
      image_gpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      model: "resnet50",
      name: "cnn-test4",
      namespace: "cnn-test",
      num_gpus: 0,
      num_ps: 1,
      num_workers: 1,
    },
    "cnn-test5": {
      batch_size: 32,
      image: "gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3",
      image_gpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      model: "resnet50",
      name: "cnn-test5",
      namespace: "cnn-test",
      num_gpus: 0,
      num_ps: 1,
      num_workers: 0,
    },
    "cnn-test6": {
      batch_size: 32,
      image: "gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3",
      image_gpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      model: "resnet50",
      name: "cnn-test6",
      namespace: "cnn-test",
      num_gpus: 0,
      num_ps: 1,
      num_workers: 0,
    },
    "cnn-test7": {
      batch_size: 32,
      image: "gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3",
      image_gpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      model: "resnet50",
      name: "cnn-test7",
      namespace: "cnn-test",
      num_gpus: 0,
      num_ps: 1,
      num_workers: 0,
    },
    "cnn-test8": {
      batch_size: 32,
      image: "gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3",
      image_gpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      model: "resnet50",
      name: "cnn-test8",
      namespace: "cnn-test",
      num_gpus: 0,
      num_ps: 1,
      num_workers: 0,
    },
    "cnn-test9": {
      batch_size: 32,
      image: "gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3",
      image_gpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      model: "resnet50",
      name: "cnn-test9",
      namespace: "cnn-test",
      num_gpus: 0,
      num_ps: 1,
      num_workers: 0,
    },
    "cnn-test10": {
      batch_size: 32,
      image: "gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3",
      image_gpu: "gcr.io/kubeflow/tf-benchmarks-gpu:v20171202-bdab599-dirty-284af3",
      model: "resnet50",
      name: "cnn-test10",
      namespace: "cnn-test",
      num_gpus: 0,
      num_ps: 1,
      num_workers: 1,
    },
    "job1": {
      args: "null",
      image: "null",
      image_gpu: "null",
      name: "job1",
      namespace: "default",
      num_gpus: 0,
      num_masters: 1,
      num_ps: 0,
      num_workers: 0,
    },
    "job2": {
      args: "null",
      image: "null",
      image_gpu: "null",
      name: "job2",
      namespace: "default",
      num_gpus: 0,
      num_masters: 1,
      num_ps: 0,
      num_workers: 0,
    },
  },
}
