{
  global: {
    // User-defined global parameters; accessible to all component and environments, Ex:
    // replicas: 4,
  },
  components: {
    // Component-level parameters, defined initially from 'ks prototype use ...'
    // Each object below should correspond to a component in the components/ directory
    "myjob1": {
      args: "null",
      image: "null",
      imageGpu: "null",
      name: "myjob1",
      namespace: "default",
      numGpus: 0,
      numMaster: 1,
      numPs: 0,
      numWorkers: 0,
    },
    "myjob2": {
      args: "null",
      image: "null",
      imageGpu: "null",
      name: "myjob2",
      namespace: "default",
      numGpus: 0,
      numMaster: 1,
      numPs: 0,
      numWorkers: 0,
    },
    "myjob3": {
      args: "null",
      image: "null",
      imageGpu: "null",
      name: "myjob3",
      namespace: "default",
      numGpus: 0,
      numMaster: 1,
      numPs: 0,
      numWorkers: 0,
    },
    "myjob4": {
      args: "null",
      image: "null",
      imageGpu: "null",
      name: "myjob4",
      namespace: "default",
      numGpus: 0,
      numMaster: 1,
      numPs: 0,
      numWorkers: 0,
    },
    "myjob5": {
      args: "null",
      image: "null",
      imageGpu: "null",
      name: "myjob5",
      namespace: "default",
      numGpus: 0,
      numMaster: 1,
      numPs: 0,
      numWorkers: 0,
    },
    "myjob6": {
      args: "null",
      image: "gcr.io/my/image",
      imageGpu: "null",
      name: "myjob6",
      namespace: "default",
      numGpus: 0,
      numMasters: 1,
      numPs: 0,
      numWorkers: 5,
    },
    "myjob7": {
      args: "null",
      image: "null",
      imageGpu: "null",
      name: "myjob7",
      namespace: "default",
      numGpus: 0,
      numMasters: 1,
      numPs: 0,
      numWorkers: 0,
    },
    "myjob8": {
      args: "--arg1=2,--arg2=3",
      image: "null",
      imageGpu: "null",
      name: "myjob8",
      namespace: "default",
      newarg: 100,
      numGpus: 0,
      numMasters: 1,
      numPs: 0,
      numWorkers: 0,
    },
  },
}
