apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
namePrefix: volumes-web-app-
namespace: kubeflow
labels:
- includeSelectors: true
  pairs:
    app: volumes-web-app
    kustomize.component: volumes-web-app
images:
- name: ghcr.io/kubeflow/kubeflow/volumes-web-app
  newName: ghcr.io/kubeflow/kubeflow/volumes-web-app
  newTag: v1.10.0
# We need the name to be unique without the suffix because the original name is what
# gets used with patches
configMapGenerator:
- envs:
  - params.env
  name: parameters
- files:
  - viewer-spec.yaml
  name: viewer-spec
replacements:
- source:
    kind: ConfigMap
    name: volumes-web-app-parameters
    fieldPath: data.VWA_PREFIX
  targets:
  - select:
      kind: Deployment
      name: volumes-web-app-deployment
    fieldPaths:
    - spec.template.spec.containers.[name=volumes-web-app].env.[name=APP_PREFIX].value
- source:
    kind: ConfigMap
    name: volumes-web-app-parameters
    fieldPath: data.VWA_USERID_HEADER
  targets:
  - select:
      kind: Deployment
      name: volumes-web-app-deployment
    fieldPaths:
    - spec.template.spec.containers.[name=volumes-web-app].env.[name=USERID_HEADER].value
- source:
    kind: ConfigMap
    name: volumes-web-app-parameters
    fieldPath: data.VWA_USERID_PREFIX
  targets:
  - select:
      kind: Deployment
      name: volumes-web-app-deployment
    fieldPaths:
    - spec.template.spec.containers.[name=volumes-web-app].env.[name=USERID_PREFIX].value
- source:
    kind: ConfigMap
    name: volumes-web-app-parameters
    fieldPath: data.VWA_APP_SECURE_COOKIES
  targets:
  - select:
      kind: Deployment
      name: volumes-web-app-deployment
    fieldPaths:
    - spec.template.spec.containers.[name=volumes-web-app].env.[name=APP_SECURE_COOKIES].value
- source:
    kind: ConfigMap
    name: volumes-web-app-parameters
    fieldPath: data.VWA_APP_ENABLE_METRICS
  targets:
  - select:
      kind: Deployment
      name: volumes-web-app-deployment
    fieldPaths:
    - spec.template.spec.containers.[name=volumes-web-app].env.[name=METRICS].value
