apiVersion: v1
kind: Secret
metadata:
  name: qnap
  namespace: dm1261010
data:
  ip: MTAuMTAwLjQuNzA=
  username: cW5hcHVzZXI=
  password: UEBzc3cwcmQ=

---

apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: copy
  namespace: dm1261010
  resourceVersion: "101137805"
spec:
  template:
    spec:
      containers:
      - image: cguaicadmin/newlab-newpytorch:V1.0.23
        imagePullPolicy: IfNotPresent
        name: copy
        resources:
          limits:
            cpu: "9.6"
            memory: 19.0Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "8"
            memory: 15.8Gi
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /home/jovyan
          name: copy-volume
      - env: 
        - name: IP
          valueFrom:
            secretKeyRef:
              name: qnap
              key: ip
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: qnap
              key: password
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: qnap
              key: username
        args:
        - -c
        - if [ ! -f /home/jovyan/.clonedone ]; then python /script.py dm1261010 copy-source-volume copy-volume ; touch /home/jovyan/.clonedone; sleep 365d; else sleep 365d; fi
        command:
        - /bin/sh
        image: vert951/qnapcopy:v0.1.3
        name: clone
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi
        volumeMounts:
        - mountPath: /source
          name: copy-source-volume
        - mountPath: /home/jovyan
          name: copy-volume
      serviceAccountName: default-editor
      tolerations: []
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: copy-volume
        persistentVolumeClaim:
          claimName: copy-volume
      - name: copy-source-volume
        persistentVolumeClaim:
          claimName: copy-source-volume
