#!/usr/bin/env bash

cleanup()
{
  if [[ -f $tmpfile ]]; then
    rm -f $tmpfile
  fi
}
trap cleanup EXIT

if (( $# == 0 )); then
  echo "usage: $0 <namespace>"
  exit 1
fi

printuserandnamespace()
{
  kubectl config get-contexts | grep '^*' | awk '{printf("user=%s namespace=%s\n",$4,$5)}'
}

tmpfile=$(mktemp)
user=$(printuserandnamespace | awk '{print $1}' | sed 's/^user=//' | tr -cd '[:print:]\n')
composition=$1

cat << USER_YAML > $tmpfile
---
apiVersion: kubeflow.org/v1alpha1
kind: Ensemble
metadata:
  name: $composition
  namespace: kubeflow
spec:
  template:
    metadata:
      name: $composition
    spec:
      namespace: $composition
      owner: $user
USER_YAML

kubectl apply -f $tmpfile
