#!/command/with-contenv bash

cd "${HOME}"
echo "INFO: starting code-server..."
exec 2>&1
exec /usr/bin/code-server \
  --bind-addr 0.0.0.0:8888 \
  --disable-telemetry \
  --disable-update-check \
  --disable-workspace-trust \
  --disable-getting-started-override \
  --auth none \
  "${HOME}"
