// Copyright 2018 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubeflow/kubeflow/bootstrap/pkg/apis/apps/v1alpha1"
	scheme "github.com/kubeflow/kubeflow/bootstrap/pkg/client/kfapi/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KsAppsGetter has a method to return a KsAppInterface.
// A group's client should implement this interface.
type KsAppsGetter interface {
	KsApps(namespace string) KsAppInterface
}

// KsAppInterface has methods to work with KsApp resources.
type KsAppInterface interface {
	Create(*v1alpha1.KsApp) (*v1alpha1.KsApp, error)
	Update(*v1alpha1.KsApp) (*v1alpha1.KsApp, error)
	UpdateStatus(*v1alpha1.KsApp) (*v1alpha1.KsApp, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KsApp, error)
	List(opts v1.ListOptions) (*v1alpha1.KsAppList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KsApp, err error)
	KsAppExpansion
}

// ksApps implements KsAppInterface
type ksApps struct {
	client rest.Interface
	ns     string
}

// newKsApps returns a KsApps
func newKsApps(c *AppsV1alpha1Client, namespace string) *ksApps {
	return &ksApps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ksApp, and returns the corresponding ksApp object, and an error if there is any.
func (c *ksApps) Get(name string, options v1.GetOptions) (result *v1alpha1.KsApp, err error) {
	result = &v1alpha1.KsApp{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ksapps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KsApps that match those selectors.
func (c *ksApps) List(opts v1.ListOptions) (result *v1alpha1.KsAppList, err error) {
	result = &v1alpha1.KsAppList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ksapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ksApps.
func (c *ksApps) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ksapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a ksApp and creates it.  Returns the server's representation of the ksApp, and an error, if there is any.
func (c *ksApps) Create(ksApp *v1alpha1.KsApp) (result *v1alpha1.KsApp, err error) {
	result = &v1alpha1.KsApp{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ksapps").
		Body(ksApp).
		Do().
		Into(result)
	return
}

// Update takes the representation of a ksApp and updates it. Returns the server's representation of the ksApp, and an error, if there is any.
func (c *ksApps) Update(ksApp *v1alpha1.KsApp) (result *v1alpha1.KsApp, err error) {
	result = &v1alpha1.KsApp{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ksapps").
		Name(ksApp.Name).
		Body(ksApp).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *ksApps) UpdateStatus(ksApp *v1alpha1.KsApp) (result *v1alpha1.KsApp, err error) {
	result = &v1alpha1.KsApp{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ksapps").
		Name(ksApp.Name).
		SubResource("status").
		Body(ksApp).
		Do().
		Into(result)
	return
}

// Delete takes name of the ksApp and deletes it. Returns an error if one occurs.
func (c *ksApps) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ksapps").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ksApps) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ksapps").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched ksApp.
func (c *ksApps) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KsApp, err error) {
	result = &v1alpha1.KsApp{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ksapps").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
