ARG BASE_CONTAINER=platiagro/platiagro-notebook-image:0.2.0
FROM $BASE_CONTAINER

WORKDIR /app

ENV MODEL_NAME Model
ENV API_TYPE REST
ENV SERVICE_TYPE MODEL
ENV PERSISTENCE 0
ENV PARAMETERS '[]'
ENV LOG_LEVEL DEBUG

EXPOSE 5000
CMD ["sh", "-c", "seldon-core-microservice \"$MODEL_NAME\" \"$API_TYPE\" --service-type \"$SERVICE_TYPE\" --persistence \"$PERSISTENCE\" --parameters \"$PARAMETERS\" --log-level \"$LOG_LEVEL\""]
