apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: ci-profile-controller
spec:
  pipelineRef:
    name: ci-pipeline
  resources:
  - name: kubeflow
    resourceRef:
      name: kubeflow
  - name: manifests
    resourceRef:
      name: manifests
  - name: $(image_name)
    resourceRef:
      name: $(image_name)
  serviceAccount: ci-pipeline-run-service-account
