name: KFAM Multi-Arch Build Test
on:
  pull_request:
    paths:
      - components/access-management/**
      - releasing/version/VERSION
    branches:
      - master
      - v*-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

env:
  IMG: kfam

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      with:
        # see: https://github.com/tonistiigi/binfmt/issues/215
        # see: https://github.com/docker/setup-qemu-action/issues/198
        image: tonistiigi/binfmt:qemu-v7.0.0-28

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build multi-arch Image
      run: |
        cd components/access-management
        ARCH=linux/amd64 make docker-build-multi-arch
        ARCH=linux/ppc64le make docker-build-multi-arch
        ARCH=linux/arm64/v8 make docker-build-multi-arch
