name: Run PVCViewer Controller unit tests
on:
  pull_request:
    paths:
      - components/pvcviewer-controller/**
      - releasing/version/VERSION
    branches:
      - master
      - v*-branch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22.2"
        check-latest: true

    - name: Run unit tests
      run: |
        cd components/pvcviewer-controller
        make test
