name: Run PVCViewer Controller unit tests
on:
  pull_request:
    paths:
      - components/pvcviewer-controller/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.2'
        check-latest: true

    - name: Run unit tests
      run: |
        cd components/pvcviewer-controller
        make test
