name: Python Linting

on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - "**.py"

jobs:
  flake8-lint:
    runs-on: ubuntu-22.04
    name: Check
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set up Python environment 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          exclude: "docs"
