name: Semantic PRs

on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  validate_title:
    name: Validate Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            improve
            refactor
            revert
            test
            ci
            docs
            chore

          scopes: |
            dashboard
            kfam
            notebook
            poddefault
            profile
            tensorboard
            volume
          requireScope: false